import 'package:PiliPlus/grpc/bilibili/community/service/dm/v1.pb.dart'
    show DanmakuElem;

/// 弹幕转 ASS 的渲染参数。
///
/// 默认值与 `Pref` 中弹幕设置的默认值保持一致，便于在无 GStorage 的环境
/// (如单元测试) 中直接使用。
class AssOptions {
  const AssOptions({
    this.playResX = 1920,
    this.playResY = 1080,
    required this.referenceHeight,
    this.fontName = '黑体',
    this.fontScale = 1.0,
    this.lineHeight = 1.6,
    this.scrollDuration = 7.0,
    this.staticDuration = 4.0,
    this.strokeWidth = 1.5,
    this.opacity = 1.0,
    this.showArea = 1.0,
    this.bold = true,
    this.blockTypes = const <int>{},
    this.weightThreshold = 0,
  });

  /// 播放器普通弹幕的基准字号，见 `DanmakuOptions.get`。
  ///
  /// 播放器对所有普通弹幕使用同一字号，并不理会 `DanmakuElem.fontsize`。
  static const double playerBaseFontSize = 15;

  /// 视频宽高，作为 ASS 的 `PlayResX`/`PlayResY`。
  final int playResX;
  final int playResY;

  /// 播放器渲染弹幕时画面的逻辑高度。
  ///
  /// 播放器的字号与描边以逻辑像素为单位，导出以视频像素为单位，靠该高度换算，
  /// 使导出结果与用户在本机看到的观感一致。由调用方从真实显示尺寸取得。
  final double referenceHeight;

  final String fontName;

  /// 字号缩放系数。
  final double fontScale;

  /// 行高系数，决定弹幕轨道间距。
  final double lineHeight;

  /// 滚动弹幕从右侧进入到完全离开左侧所需秒数。
  final double scrollDuration;

  /// 顶部/底部弹幕的停留秒数。
  final double staticDuration;

  /// 描边宽度，语义与播放器一致（居中于字形轮廓）。
  final double strokeWidth;

  /// 不透明度，0~1。
  final double opacity;

  /// 弹幕可用显示区域占画面高度的比例，0~1。
  final double showArea;

  final bool bold;

  /// 需要屏蔽的弹幕类型：2 滚动、4 底部、5 顶部、6 彩色、7 高级。
  final Set<int> blockTypes;

  /// 屏蔽等级低于该值的弹幕。
  final int weightThreshold;

  /// 视频像素相对播放器逻辑像素的缩放。
  double get _resolutionScale =>
      referenceHeight > 0 ? playResY / referenceHeight : 1.0;

  /// 实际字号。所有普通弹幕共用，与播放器一致。
  double get fontSize => playerBaseFontSize * fontScale * _resolutionScale;

  /// ASS 的 `Outline` 是全额向外扩，而播放器的描边居中于字形轮廓，
  /// 只向外扩一半，故取半值才能观感一致。
  double get outline => strokeWidth / 2 * _resolutionScale;
}

/// 弹幕位置类型。
enum _Lane { scroll, top, bottom }

/// 已占用的滚动轨道信息。
class _ScrollSlot {
  const _ScrollSlot({
    required this.enterMs,
    required this.leaveMs,
    required this.width,
    required this.speed,
  });

  /// 弹幕出现时刻。
  final int enterMs;

  /// 弹幕右边缘完全离开画面的时刻。
  final int leaveMs;

  final double width;

  /// 像素 / 毫秒。
  final double speed;
}

abstract final class AssUtils {
  static const String _assHeaderStyleName = 'Danmaku';

  /// 把 [elems] 转换为 ASS 字幕文本。
  ///
  /// 会按 `id` 去重 (缓存的 `danmaku.pb` 是多段合并而来，重复下载可能产生重复
  /// 项)，并按时间排序后做轨道分配；无可用轨道的弹幕被丢弃，与播放器行为一致。
  ///
  /// 高级弹幕 (mode 7) 与 BAS 弹幕 (mode 9) 不被转换。
  static String danmaku2Ass(
    Iterable<DanmakuElem> elems, {
    required String title,
    required AssOptions options,
  }) {
    final sb = StringBuffer()
      ..writeln('[Script Info]')
      ..writeln('; Generated by PiliSuper')
      ..writeln('Title: ${_sanitizeHeader(title)}')
      ..writeln('ScriptType: v4.00+')
      ..writeln('WrapStyle: 2')
      ..writeln('ScaledBorderAndShadow: yes')
      ..writeln('PlayResX: ${options.playResX}')
      ..writeln('PlayResY: ${options.playResY}')
      ..writeln()
      ..writeln('[V4+ Styles]')
      ..writeln(
        'Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, '
        'OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, '
        'ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, '
        'Alignment, MarginL, MarginR, MarginV, Encoding',
      )
      ..writeln(_buildStyle(options))
      ..writeln()
      ..writeln('[Events]')
      ..writeln(
        'Format: Layer, Start, End, Style, Name, MarginL, MarginR, '
        'MarginV, Effect, Text',
      );

    for (final event in _layout(elems, options)) {
      sb.writeln(event);
    }
    return sb.toString();
  }

  static String _buildStyle(AssOptions options) {
    // 弹幕自身携带颜色，样式里的主色只提供透明度基准。
    final alpha = _alphaHex(options.opacity);
    return 'Style: $_assHeaderStyleName,${options.fontName},'
        '${_num(options.fontSize)},'
        '&H${alpha}FFFFFF,&H${alpha}FFFFFF,&H${alpha}000000,&H${alpha}000000,'
        '${options.bold ? -1 : 0},0,0,0,100,100,0,0,1,'
        '${_num(options.outline)},0,7,0,0,0,1';
  }

  /// 轨道分配，返回 Dialogue 行。
  static List<String> _layout(Iterable<DanmakuElem> elems, AssOptions options) {
    final sorted = _prepare(elems, options);
    if (sorted.isEmpty) return const [];

    final scrollMs = (options.scrollDuration * 1000).round();
    final staticMs = (options.staticDuration * 1000).round();

    final events = <String>[];
    // 每条轨道的占用情况，索引即轨道号。
    final scrollSlots = <int, _ScrollSlot>{};
    final topSlots = <int, int>{};
    final bottomSlots = <int, int>{};

    for (final elem in sorted) {
      final lane = _laneOf(elem.mode);
      final fontSize = options.fontSize;
      final rowHeight = fontSize * options.lineHeight;
      final maxRows = _maxRows(options, rowHeight);
      if (maxRows == 0) continue;

      final width = _textWidth(elem.content, fontSize);
      final start = elem.progress;
      final text = _escape(elem.content);
      final colorTag = _colorTag(elem.color);
      // 静态弹幕水平居中。用 ASS 的居中对齐让渲染器按实际字形宽度定位，
      // 而不是依赖这里的宽度估算，否则会整体偏左。
      final centerX = _num(options.playResX / 2);

      switch (lane) {
        case _Lane.scroll:
          // 速度以「整条弹幕从右边缘之外走到左边缘之外」为一个周期。
          final speed = (options.playResX + width) / scrollMs;
          final leave = start + scrollMs;
          final row = _findScrollRow(
            scrollSlots,
            maxRows,
            start: start,
            width: width,
            speed: speed,
          );
          if (row == null) continue;
          scrollSlots[row] = _ScrollSlot(
            enterMs: start,
            leaveMs: leave,
            width: width,
            speed: speed,
          );
          final y = _num(row * rowHeight);
          events.add(
            _dialogue(
              start: start,
              end: leave,
              options: options,
              tags:
                  '\\move(${options.playResX},$y,${_num(-width)},$y)$colorTag',
              text: text,
            ),
          );

        case _Lane.top:
          final end = start + staticMs;
          final row = _findStaticRow(topSlots, maxRows, start);
          if (row == null) continue;
          topSlots[row] = end;
          final y = _num(row * rowHeight);
          events.add(
            _dialogue(
              start: start,
              end: end,
              options: options,
              // an8：锚点为文字上边中点。
              tags: '\\an8\\pos($centerX,$y)$colorTag',
              text: text,
            ),
          );

        case _Lane.bottom:
          final end = start + staticMs;
          final row = _findStaticRow(bottomSlots, maxRows, start);
          if (row == null) continue;
          bottomSlots[row] = end;
          // 底部弹幕自下往上堆叠。
          final y = _num(options.playResY - row * rowHeight);
          events.add(
            _dialogue(
              start: start,
              end: end,
              options: options,
              // an2：锚点为文字下边中点。
              tags: '\\an2\\pos($centerX,$y)$colorTag',
              text: text,
            ),
          );
      }
    }
    return events;
  }

  /// 去重 + 过滤 + 排序。
  static List<DanmakuElem> _prepare(
    Iterable<DanmakuElem> elems,
    AssOptions options,
  ) {
    final seen = <int>{};
    final result = <DanmakuElem>[];
    for (final elem in elems) {
      // 高级弹幕/BAS 弹幕无法用普通 ASS 事件表达。
      if (elem.mode == 7 || elem.mode == 9) continue;
      if (elem.content.isEmpty) continue;
      if (elem.weight < options.weightThreshold) continue;
      if (options.blockTypes.contains(_blockTypeOf(elem.mode))) continue;
      if (!seen.add(elem.id.toInt())) continue;
      result.add(elem);
    }
    result.sort((a, b) => a.progress.compareTo(b.progress));
    return result;
  }

  static _Lane _laneOf(int mode) => switch (mode) {
    4 => _Lane.bottom,
    5 => _Lane.top,
    _ => _Lane.scroll,
  };

  /// 弹幕 mode 到设置里屏蔽类型编号的映射。
  static int _blockTypeOf(int mode) => switch (mode) {
    4 => 4,
    5 => 5,
    _ => 2,
  };

  static int _maxRows(AssOptions options, double rowHeight) {
    if (rowHeight <= 0) return 0;
    final usable = options.playResY * options.showArea;
    return (usable / rowHeight).floor().clamp(0, 1 << 20);
  }

  /// 找到不会与已有弹幕重叠或追尾的滚动轨道。
  static int? _findScrollRow(
    Map<int, _ScrollSlot> slots,
    int maxRows, {
    required int start,
    required double width,
    required double speed,
  }) {
    for (var row = 0; row < maxRows; row++) {
      final prev = slots[row];
      if (prev == null) return row;
      // 前一条已完全离开画面。
      if (prev.leaveMs <= start) return row;
      final elapsed = start - prev.enterMs;
      // 条件一：新弹幕出现时，前一条必须已完整进入画面。
      if (prev.speed * elapsed < prev.width) continue;
      // 条件二：前一条离开画面前，新弹幕不能追上它。
      if (speed * (prev.leaveMs - start) > width) continue;
      return row;
    }
    return null;
  }

  static int? _findStaticRow(Map<int, int> slots, int maxRows, int start) {
    for (var row = 0; row < maxRows; row++) {
      final endMs = slots[row];
      if (endMs == null || endMs <= start) return row;
    }
    return null;
  }

  static String _dialogue({
    required int start,
    required int end,
    required AssOptions options,
    required String tags,
    required String text,
  }) {
    // 字号统一由样式提供，与播放器一致，无需逐条覆盖。
    return 'Dialogue: 0,${_timecode(start)},${_timecode(end)},'
        '$_assHeaderStyleName,,0,0,0,,{$tags}$text';
  }

  /// `H:MM:SS.cc`
  static String _timecode(int milli) {
    if (milli < 0) milli = 0;
    final cs = milli ~/ 10;
    final h = cs ~/ 360000;
    final m = (cs ~/ 6000) % 60;
    final s = (cs ~/ 100) % 60;
    final c = cs % 100;
    return '$h:${_pad2(m)}:${_pad2(s)}.${_pad2(c)}';
  }

  static String _pad2(int value) => value.toString().padLeft(2, '0');

  /// ASS 的颜色为 `&HBBGGRR&`，弹幕颜色为 24 位 RGB。
  static String _colorTag(int color) {
    final rgb = color & 0xFFFFFF;
    if (rgb == 0xFFFFFF) return '';
    final r = (rgb >> 16) & 0xFF;
    final g = (rgb >> 8) & 0xFF;
    final b = rgb & 0xFF;
    return '\\c&H${_hex2(b)}${_hex2(g)}${_hex2(r)}&';
  }

  static String _hex2(int value) =>
      value.toRadixString(16).toUpperCase().padLeft(2, '0');

  /// ASS 透明度：00 全不透明，FF 全透明。
  static String _alphaHex(double opacity) =>
      _hex2((((1 - opacity.clamp(0.0, 1.0)) * 255).round()).clamp(0, 255));

  /// 去掉小数末尾的 `.0`，让输出更短。
  static String _num(double value) {
    final rounded = double.parse(value.toStringAsFixed(2));
    return rounded == rounded.roundToDouble()
        ? rounded.toInt().toString()
        : rounded.toString();
  }

  /// 花括号会被 libass 当作特效标签起止符，换成全角以免注入。
  static String _escape(String text) => text
      .replaceAll('{', '｛')
      .replaceAll('}', '｝')
      .replaceAll('\r\n', '\\N')
      .replaceAll('\n', '\\N')
      .replaceAll('\r', '\\N');

  static String _sanitizeHeader(String text) =>
      text.replaceAll('\r', ' ').replaceAll('\n', ' ');

  /// 粗略估算文本宽度：全角字符按 1 个字号，半角按半个字号。
  static double _textWidth(String text, double fontSize) {
    var units = 0.0;
    for (final rune in text.runes) {
      units += _isFullWidth(rune) ? 1.0 : 0.5;
    }
    return units * fontSize;
  }

  static bool _isFullWidth(int rune) =>
      (rune >= 0x1100 && rune <= 0x115F) || // 韩文字母
      (rune >= 0x2E80 && rune <= 0xA4CF) || // CJK 部首 ~ 彝文
      (rune >= 0xAC00 && rune <= 0xD7A3) || // 韩文音节
      (rune >= 0xF900 && rune <= 0xFAFF) || // CJK 兼容表意
      (rune >= 0xFE30 && rune <= 0xFE6F) || // CJK 兼容形式
      (rune >= 0xFF00 && rune <= 0xFF60) || // 全角形式
      (rune >= 0xFFE0 && rune <= 0xFFE6) ||
      (rune >= 0x1F300 && rune <= 0x1F9FF); // emoji
}
