name: Build

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - "**.md"
  workflow_dispatch:
    inputs:
      tag:
        description: "Release tag（留空则只构建不发布）"
        required: false
        default: ""
        type: string
      pkg_id:
        description: "包名（留空则使用默认值）"
        required: false
        default: "com.pili.super"
        type: string
      app_name:
        description: "应用名（留空则使用默认值）"
        required: false
        default: "PiliSuper"
        type: string
      build_android:
        description: "Build Android"
        default: true
        type: boolean
      build_ios:
        description: "Build iOS"
        default: true
        type: boolean
      build_macos:
        description: "Build macOS"
        default: true
        type: boolean
      build_windows:
        description: "Build Windows"
        default: true
        type: boolean
      build_linux:
        description: "Build Linux"
        default: true
        type: boolean

# ─────────────────────────────────────────────────────────────────

jobs:

  # ───────────── Android ─────────────
  android:
    name: Android
    if: ${{ github.event_name == 'pull_request' || inputs.build_android == true }}
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v5
        with:
          distribution: zulu
          java-version: "17"
          cache: gradle
          cache-dependency-path: |
            android/*.gradle*
            android/**/gradle-wrapper.properties

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
          cache: true

      - name: Add Rename CLI tool
        run: |
            dart pub global activate rename

      - name: Build
        env:
          KEYSTORE_B64: ${{ secrets.SIGN_KEYSTORE_BASE64 }}
          KEY_ALIAS:    ${{ secrets.KEY_ALIAS }}
          KEY_PASS:     ${{ secrets.KEY_PASSWORD }}
          STORE_PASS:   ${{ secrets.KEYSTORE_PASSWORD }}
        run: |
          SIGN_ARGS=()
          if [[ "${{ github.event_name }}" == "workflow_dispatch" && -n "$KEYSTORE_B64" ]]; then
            SIGN_ARGS+=(
              --sign
              --keystore-base64 "$KEYSTORE_B64"
              --key-alias       "$KEY_ALIAS"
              --key-password    "$KEY_PASS"
              --store-password  "$STORE_PASS"
              --clean-keys
            )
          fi

          NAME_ARGS=()
          if [[ -n "${{ inputs.app_name }}" ]]; then
            NAME_ARGS+=(
              --app-name "${{ inputs.app_name }}"
            )
          fi

          if [[ -n "${{ inputs.pkg_id }}" ]]; then
            NAME_ARGS+=(
              --pkg-id "${{ inputs.pkg_id }}"
            )
          fi

          python3 build.py android \
            --output-prefix PiliSuper \
            --output dist \
            "${SIGN_ARGS[@]}" \
            "${NAME_ARGS[@]}" \

      - name: Release
        if: ${{ inputs.tag != '' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag }}
          name:     ${{ inputs.tag }}
          files:    dist/PiliSuper_android_*.apk

      - uses: actions/upload-artifact@v7
        with:
          name: Android_arm64-v8a
          path: dist/PiliSuper_android_*_arm64-v8a.apk
          archive: false

      - uses: actions/upload-artifact@v7
        with:
          name: Android_armeabi-v7a
          path: dist/PiliSuper_android_*_armeabi-v7a.apk
          archive: false

      - uses: actions/upload-artifact@v7
        with:
          name: Android_x86_64
          path: dist/PiliSuper_android_*_x86_64.apk
          archive: false

  # ───────────── iOS ─────────────
  ios:
    name: iOS
    if: ${{ github.event_name == 'pull_request' || inputs.build_ios == true }}
    runs-on: macos-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
      
      - name: Add Rename CLI tool
        run: |
            dart pub global activate rename

      - name: Build
        run: |
          NAME_ARGS=()
          if [[ -n "${{ inputs.app_name }}" ]]; then
            NAME_ARGS+=(
              --app-name "${{ inputs.app_name }}"
            )
          fi

          if [[ -n "${{ inputs.pkg_id }}" ]]; then
            NAME_ARGS+=(
              --pkg-id "${{ inputs.pkg_id }}"
            )
          fi
          
          python3 build.py ios \
            "${NAME_ARGS[@]}" \
            --output-prefix PiliSuper \
            --output dist

      - name: Release
        if: ${{ inputs.tag != '' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag }}
          name:     ${{ inputs.tag }}
          files:    dist/PiliSuper_ios_*.ipa

      - uses: actions/upload-artifact@v7
        with:
          name: iOS
          path: dist/PiliSuper_ios_*.ipa
          archive: false

  # ───────────── macOS ─────────────
  macos:
    name: macOS
    if: ${{ inputs.build_macos == true }}
    runs-on: macos-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml

      - name: Install create-dmg
        run: npm install --global create-dmg

      - name: Add Rename CLI tool
        run: |
            dart pub global activate rename

      - name: Build
        run: |
          NAME_ARGS=()
          if [[ -n "${{ inputs.app_name }}" ]]; then
            NAME_ARGS+=(
              --app-name "${{ inputs.app_name }}"
            )
          fi

          if [[ -n "${{ inputs.pkg_id }}" ]]; then
            NAME_ARGS+=(
              --pkg-id "${{ inputs.pkg_id }}"
            )
          fi

          python3 build.py macos \
            "${NAME_ARGS[@]}" \
            --output-prefix PiliSuper \
            --output dist

      - name: Release
        if: ${{ inputs.tag != '' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag }}
          name:     ${{ inputs.tag }}
          files:    dist/PiliSuper_macos_*.dmg

      - uses: actions/upload-artifact@v7
        with:
          name: macOS
          path: dist/PiliSuper_macos_*.dmg
          archive: false

  # ───────────── Windows ─────────────
  windows:
    name: Windows x64
    if: ${{ github.event_name == 'pull_request' || inputs.build_windows == true }}
    runs-on: windows-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml

      - name: Install fastforge & Inno Setup
        run: |
          dart pub global activate fastforge
          choco install innosetup

      - name: Add Inno Setup Chinese language
        shell: pwsh
        run: |
          Copy-Item "windows/packaging/exe/ChineseSimplified.isl" `
            "C:\Program Files (x86)\Inno Setup 6\Languages\ChineseSimplified.isl"
      
      - name: Add Rename CLI tool
        run: |
            dart pub global activate rename

      - name: Build
        shell: bash
        run: |
          NAME_ARGS=()
          if [[ -n "${{ inputs.app_name }}" ]]; then
            NAME_ARGS+=(--app-name "${{ inputs.app_name }}")
          fi
          if [[ -n "${{ inputs.pkg_id }}" ]]; then
            NAME_ARGS+=(--pkg-id "${{ inputs.pkg_id }}")
          fi
          python build.py windows --installer \
            "${NAME_ARGS[@]}" \
            --output-prefix PiliSuper \
            --output dist

      - name: Release
        if: ${{ inputs.tag != '' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag }}
          name:     ${{ inputs.tag }}
          files: |
            dist/PiliSuper_windows_*_portable.zip
            dist/PiliSuper_windows_*_setup.exe

      - uses: actions/upload-artifact@v7
        with:
          name: Windows_portable_x64
          path: dist/PiliSuper_windows_*_portable.zip
          archive: false

      - uses: actions/upload-artifact@v7
        with:
          name: Windows_setup_x64
          path: dist/PiliSuper_windows_*_setup.exe
          archive: false

  # ───────────── Linux ─────────────
  linux:
    name: Linux x64
    if: ${{ inputs.build_linux == true }}
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            clang cmake ninja-build pkg-config \
            libgtk-3-dev libayatana-appindicator3-dev \
            libasound2-dev libmpv-dev \
            rpm patchelf webkit2gtk-4.1 \
            gcc g++ autoconf automake debhelper \
            glslang-dev ladspa-sdk xutils-dev \
            libarchive-dev libbluray-dev libbs2b-dev libcaca-dev \
            libcdio-paranoia-dev libdrm-dev libdav1d-dev libdvdnav-dev \
            libegl1-mesa-dev libepoxy-dev libfontconfig-dev libfreetype6-dev \
            libfribidi-dev libgl1-mesa-dev libgbm-dev libgme-dev libgsm1-dev \
            libharfbuzz-dev libjpeg-dev libbrotli-dev liblcms2-dev \
            libmodplug-dev libmp3lame-dev libopenal-dev libopus-dev \
            libopencore-amrnb-dev libopencore-amrwb-dev libpulse-dev \
            librtmp-dev libsdl2-dev libsixel-dev libssh-dev libsoxr-dev \
            libspeex-dev libtool libv4l-dev libva-dev libvdpau-dev \
            libvorbis-dev libvo-amrwbenc-dev libunwind-dev libvpx-dev \
            libwayland-dev libx11-dev libxext-dev libxkbcommon-dev \
            libxrandr-dev libxss-dev libxv-dev libxvidcore-dev \
            linux-libc-dev nasm wayland-protocols python3-docutils \
            x11proto-core-dev zlib1g-dev libfdk-aac-dev libtheora-dev \
            libwebp-dev unixodbc-dev libpq-dev libxxhash-dev libaom-dev \
            libgtk-3-0 libblkid1 liblzma5

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
          cache: true

      - name: Add Rename CLI tool
        run: |
            dart pub global activate rename

      - name: Build
        run: |
          NAME_ARGS=()
          if [[ -n "${{ inputs.app_name }}" ]]; then
            NAME_ARGS+=(
              --app-name "${{ inputs.app_name }}"
            )
          fi

          if [[ -n "${{ inputs.pkg_id }}" ]]; then
            NAME_ARGS+=(
              --pkg-id "${{ inputs.pkg_id }}"
            )
          fi

          python3 build.py linux \
            "${NAME_ARGS[@]}" \
            --output-prefix PiliSuper \
            --output dist \
            --linux-targets tar.gz deb rpm appimage

      - name: Release
        if: ${{ inputs.tag != '' }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag }}
          name:     ${{ inputs.tag }}
          files: |
            dist/PiliSuper_linux_*.tar.gz
            dist/PiliSuper_linux_*.deb
            dist/PiliSuper_linux_*.rpm
            dist/PiliSuper_linux_*.AppImage

      - uses: actions/upload-artifact@v7
        with:
          name: Linux_tar.gz_amd64
          path: dist/PiliSuper_linux_*.tar.gz
          archive: false

      - uses: actions/upload-artifact@v7
        with:
          name: Linux_deb_amd64
          path: dist/PiliSuper_linux_*.deb
          archive: false

      - uses: actions/upload-artifact@v7
        with:
          name: Linux_rpm_amd64
          path: dist/PiliSuper_linux_*.rpm
          archive: false

      - uses: actions/upload-artifact@v7
        with:
          name: Linux_AppImage_amd64
          path: dist/PiliSuper_linux_*.AppImage
          archive: false
